fragment userFields on User {
  id
  createdAt
  updatedAt
  email
  firstName
  lastName
  username
  phoneNumber
  grids {
    id
    createdAt
    updatedAt
    published
    name
    rows
    columns
    gridTemplateColumns
    gridTemplateRows
  }
}
